"use client";

import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import {
  X, Sparkles, MessageCircle, Search,
  Palette, Settings,
  PenSquare,
} from "lucide-react";
import { UserMeshi } from "@/components/meshi/user-meshi";
import type { MeshiColor, MeshiHat } from "./meshi-mascot";

interface MeshiActionsMenuProps {
  meshiColor: MeshiColor;
  meshiHat: MeshiHat;
  onClose: () => void;
  onAskMeshi: () => void;
  onSearchMesh: () => void;
  onOpenChat: () => void;
}

export function MeshiActionsMenu({
  onClose, onAskMeshi, onSearchMesh, onOpenChat,
}: MeshiActionsMenuProps) {
  const router = useRouter();

  const navigate = (path: string) => { onClose(); router.push(path); };

  return (
    <motion.div
      data-meshi-owned="true"
      initial={{ opacity: 0, y: 10, scale: 0.95 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, y: 10, scale: 0.95 }}
      transition={{ type: "spring", damping: 25, stiffness: 300 }}
      className="fixed bottom-[72px] lg:bottom-[72px] right-4 z-50 w-[260px] max-w-[calc(100vw-2rem)] max-h-[60vh] glass-dropdown rounded-2xl shadow-2xl overflow-hidden flex flex-col"
    >
      {/* Header */}
      <div className="flex items-center gap-3 px-4 py-3 border-b border-[var(--border-primary)]" style={{ background: "var(--bg-secondary)" }}>
        <UserMeshi size={28} />
        <div className="flex-1 min-w-0">
          <p className="text-sm font-semibold text-[var(--text-primary)]">Meshi</p>
          <p className="text-[10px] text-[var(--text-muted)]">Your bridge to the internet</p>
        </div>
        <button
          onClick={onClose}
          aria-label="Close Meshi actions"
          className="p-1.5 rounded-lg text-[var(--text-muted)] hover:text-[var(--text-secondary)] hover:bg-[var(--bg-tertiary)] transition-colors"
        >
          <X className="h-4 w-4" />
        </button>
      </div>

      {/* Menu Items */}
      <div className="grid grid-cols-2 gap-2 p-2">
        <MenuItem icon={Sparkles} iconColor="var(--accent)" label="Ask" onClick={onAskMeshi} />
        <MenuItem icon={MessageCircle} iconColor="#a78bfa" label="Chat" onClick={onOpenChat} />
        <MenuItem icon={PenSquare} iconColor="#34d399" label="Post" onClick={() => navigate("/feed?compose=true")} />
        <MenuItem icon={Search} iconColor="#f59e0b" label="Explore" onClick={onSearchMesh} />
      </div>

      {/* Footer */}
      <div className="px-4 py-2 border-t border-[var(--border-primary)] flex items-center justify-between" style={{ background: "var(--bg-secondary)" }}>
        <button
          onClick={() => navigate("/settings?tab=meshi")}
          className="flex items-center gap-1 text-[10px] text-[var(--text-muted)] hover:text-[var(--text-secondary)] transition-colors"
        >
          <Palette className="h-3 w-3" />
          Customize
        </button>
        {/* Was an emerald pulsing "Private first" — the same padlock grammar
            removed from the chat header, on the FIRST panel every user sees when
            they tap Meshi. Meshi's replies are generated by a third-party
            provider, so the pill states that instead, in neutral colour and
            without the pulse. */}
        <span
          className="rounded-full bg-[var(--bg-tertiary)] px-1.5 py-0.5 text-[9px] font-medium text-[var(--text-muted)]"
          title="Meshi's replies are generated by a third-party AI provider. What Meshi may send is governed by your Meshi memory rule in Privacy controls."
        >
          Cloud AI
        </span>
        <button onClick={() => navigate("/settings")} aria-label="Open settings" className="text-[var(--text-muted)] hover:text-[var(--text-secondary)] transition-colors">
          <Settings className="h-3.5 w-3.5" />
        </button>
      </div>
    </motion.div>
  );
}

function MenuItem({ icon: Icon, iconColor, label, onClick }: {
  icon: React.ComponentType<{ className?: string; style?: React.CSSProperties }>;
  iconColor: string;
  label: string;
  onClick: () => void;
}) {
  return (
    <button
      onClick={onClick}
      className="flex min-h-[72px] flex-col items-center justify-center gap-2 rounded-xl px-3 py-3 text-center hover:bg-[var(--bg-hover)] transition-colors"
      style={{ color: "var(--text-primary)" }}
    >
      <Icon className="h-4 w-4" style={{ color: iconColor }} />
      <span className="text-sm font-semibold">{label}</span>
    </button>
  );
}
