"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Send, Sparkles, Search, BarChart3, Shield, HelpCircle, PenLine, UserPlus, MessageSquare } from "lucide-react";
import { askMeshi, runMeshiAction } from "@/lib/meshi-client";
import type { MeshiAction, MeshiContext, MeshiHistoryMessage } from "@/lib/meshi-shared";
import type { MeshGraphEntity } from "@/lib/queries";
import { UserMeshi } from "@/components/meshi/user-meshi";
import type { MeshiAccessory, MeshiHat, MeshiColor, MeshiHair, MeshiMood } from "./meshi-mascot";

interface ChatMessage {
  id: string;
  role: "user" | "meshi";
  content: string;
  timestamp: Date;
  /** Vessel action Meshi proposed with this message; rendered as live controls. */
  action?: MeshiAction;
  actionDone?: boolean;
}

const QUICK_ACTIONS = [
  { icon: Search, label: "Search", prompt: "Search my Mesh" },
  { icon: BarChart3, label: "Summary", prompt: "Summarize my Mesh" },
  { icon: Shield, label: "Privacy", prompt: "How is my privacy looking?" },
  { icon: HelpCircle, label: "Help", prompt: "Explain how Mesh.me works" },
];

interface MeshiChatProps {
  isOpen: boolean;
  onClose: () => void;
  hat?: MeshiHat;
  color?: MeshiColor;
  hair?: MeshiHair;
  accessory?: MeshiAccessory;
  faceStyle?: string;
  meshData?: {
    followers?: number;
    following?: number;
    posts?: number;
    communities?: number;
    platforms?: number;
  };
  meshEntities?: MeshGraphEntity[];
  focusedContent?: MeshiContext["focusedContent"];
}

function toMeshiHistory(messages: ChatMessage[]): MeshiHistoryMessage[] {
  return messages
    .filter((message) => message.id !== "welcome")
    .slice(-8)
    .map((message) => ({
      role: message.role,
      content: message.content,
    }));
}

export function MeshiChat({
  isOpen,
  onClose,
  meshData,
  meshEntities,
  focusedContent,
}: MeshiChatProps) {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: "welcome",
      role: "meshi",
      // "Privacy stays first" was the first thing Meshi said, directly above an
      // input whose contents go to a third-party provider. Not false exactly —
      // an intent, not a mechanism — but it was doing the same reassuring work
      // as the emerald "Private" pill this change removed, in the same moment.
      // Replaced with something true AND useful: the switch it names really does
      // gate both the grounding query and the egress.
      content: "Hi. I'm Meshi. Ask me to search, explain, or help with your Mesh. You decide what I can see in Privacy controls.",
      timestamp: new Date(),
    },
  ]);
  const [input, setInput] = useState("");
  const [meshiMood, setMeshiMood] = useState<MeshiMood>("happy");
  const [isTyping, setIsTyping] = useState(false);
  // Not "Private companion" — Meshi's replies are generated by a third-party
  // provider, so "private" is the one word this label must not use.
  const [statusLabel, setStatusLabel] = useState("Your mesh companion");
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen || isTyping) return;
    queueMicrotask(() => setMeshiMood("happy"));
  }, [isOpen, isTyping]);

  const handleSend = useCallback((text?: string) => {
    const messageText = text || input.trim();
    if (!messageText || isTyping) return;

    const previousMessages = messages;
    const userMsg: ChatMessage = {
      id: `user-${Date.now()}`,
      role: "user",
      content: messageText,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setIsTyping(true);
    setMeshiMood("thinking");
    setStatusLabel("Thinking with Mesh context");

    void (async () => {
      const response = await askMeshi({
        message: messageText,
        context: {
          meshData,
          meshEntities: meshEntities?.slice(0, 50),
          focusedContent,
          currentPage: typeof window === "undefined" ? undefined : window.location.pathname,
        },
        history: toMeshiHistory(previousMessages),
      });

      setMeshiMood(response.mood as MeshiMood);
      setStatusLabel(
        response.source === "engine"
          ? "Meshi engine + Mesh context"
          : response.source === "database"
            ? "Mesh data answer"
            : response.source === "offline"
              ? "Offline fallback"
              : "Local safety fallback",
      );
      setMessages((prev) => [
        ...prev,
        {
          id: `meshi-${Date.now()}`,
          role: "meshi",
          content: response.content,
          timestamp: new Date(),
          action: response.action,
        },
      ]);
      setIsTyping(false);

      // Suggestions are read-only, so Meshi fetches them right away instead of
      // asking permission first.
      if (response.action?.type === "suggest") {
        setIsTyping(true);
        const result = await runMeshiAction({
          action: "suggest",
          suggestionType: (response.action.suggestionType as "people" | "communities" | "content") || "people",
        });
        setMeshiMood(result.mood);
        setMessages((prev) => [
          ...prev.map((m) => (m.action?.type === "suggest" ? { ...m, actionDone: true } : m)),
          { id: `meshi-${Date.now()}-suggest`, role: "meshi" as const, content: result.message, timestamp: new Date() },
        ]);
        setIsTyping(false);
      }
    })();
  }, [input, isTyping, meshData, meshEntities, focusedContent, messages]);

  const confirmPostAction = useCallback((messageId: string, action: MeshiAction) => {
    const content = action.content;
    if (!content || isTyping) return;
    setMessages((prev) => prev.map((m) => (m.id === messageId ? { ...m, actionDone: true } : m)));
    setIsTyping(true);
    setMeshiMood("thinking");
    setStatusLabel("Acting on your behalf");

    void (async () => {
      const result = await runMeshiAction({ action: "post", content });
      setMeshiMood(result.mood);
      setStatusLabel(result.success ? "Vessel action complete" : "Vessel action failed");
      setMessages((prev) => [
        ...prev,
        { id: `meshi-${Date.now()}-action`, role: "meshi" as const, content: result.message, timestamp: new Date() },
      ]);
      setIsTyping(false);
    })();
  }, [isTyping]);

  const dismissAction = useCallback((messageId: string) => {
    setMessages((prev) => prev.map((m) => (m.id === messageId ? { ...m, actionDone: true } : m)));
  }, []);

  const prefillFromPrompt = useCallback((template: string) => {
    setInput(template);
    inputRef.current?.focus();
  }, []);

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          data-meshi-owned="true"
          initial={{ opacity: 0, y: 16, scale: 0.62 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 16, scale: 0.62 }}
          transition={{ type: "spring", damping: 26, stiffness: 320 }}
          style={{ transformOrigin: "bottom right" }}
          className="fixed bottom-[calc(5.75rem+env(safe-area-inset-bottom))] right-3 z-50 flex h-[calc(100dvh-9rem)] min-h-[22rem] max-h-[520px] w-[calc(100vw-1.5rem)] max-w-[360px] flex-col overflow-hidden rounded-2xl shadow-2xl glass-dropdown sm:bottom-4 sm:right-4 sm:h-[520px] sm:max-h-[calc(100dvh-6rem)] sm:w-[360px]"
        >
          <div className="flex items-center gap-3 border-b border-[var(--border-primary)] px-4 py-3" style={{ background: "var(--bg-secondary)" }}>
            <UserMeshi size={36} mood={isTyping ? "thinking" : meshiMood} />
            <div className="min-w-0 flex-1">
              <p className="text-sm font-semibold text-[var(--text-primary)]">Meshi</p>
              <p className="text-micro text-[var(--text-muted)]">{isTyping ? "Thinking..." : statusLabel}</p>
            </div>
            <div className="flex items-center gap-1">
              {/* This pill used to read "Private" in emerald with a pulsing dot —
                  the visual grammar of a padlock — while the message being typed
                  under it, plus the mesh context, went to a third-party model
                  provider. A false security indicator is worse than none: it is
                  read at the exact moment someone decides what to type.

                  Replaced with what is true, in neutral colour and without the
                  pulse. It states the upper bound: some answers are served
                  locally by the engine, but any of them MAY go to the provider,
                  and that is the direction it is safe to be wrong in. */}
              <span
                className="rounded-full bg-[var(--bg-tertiary)] px-2 py-0.5 text-micro font-medium text-[var(--text-muted)]"
                title="Meshi's replies are generated by a third-party AI provider. What Meshi may send is governed by your Meshi memory rule in Privacy controls."
              >
                Cloud AI
              </span>
              <button
                onClick={onClose}
                aria-label="Close Meshi chat"
                className="rounded-lg p-1.5 text-[var(--text-muted)] transition-colors hover:bg-[var(--bg-tertiary)] hover:text-[var(--text-secondary)]"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          </div>

          <div className="flex-1 space-y-3 overflow-y-auto p-4" style={{ background: "var(--bg-primary)" }}>
            {messages.map((msg, index) => {
              const fromRight = msg.role === "user";
              // Cascade consecutive same-role bubbles (multi-part replies) on entrance.
              let runPos = 0;
              for (let i = index - 1; i >= 0 && messages[i].role === msg.role; i -= 1) runPos += 1;
              return (
              <motion.div
                key={msg.id}
                initial={{ opacity: 0, x: fromRight ? 24 : -24, y: 6, scale: 0.94 }}
                animate={{ opacity: 1, x: 0, y: 0, scale: 1 }}
                transition={{ type: "spring", stiffness: 360, damping: 26, delay: Math.min(runPos * 0.06, 0.24) }}
                className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
              >
                <div
                  className={`max-w-[85%] whitespace-pre-line rounded-2xl px-3.5 py-2.5 text-[0.78125rem] leading-relaxed ${
                    msg.role === "user"
                      ? "brand-button rounded-br-md text-white"
                      : "rounded-bl-md border border-[var(--border-primary)] bg-[var(--bg-card)] text-[var(--text-primary)]"
                  }`}
                >
                  {msg.content}
                  {msg.role === "meshi" && msg.action && !msg.actionDone && (
                    <div className="mt-2 flex flex-wrap gap-1.5">
                      {msg.action.type === "post" && msg.action.content && (
                        <>
                          <button
                            onClick={() => confirmPostAction(msg.id, msg.action!)}
                            className="flex items-center gap-1 rounded-lg brand-button px-2.5 py-1 text-micro font-semibold text-white transition-all hover:shadow"
                          >
                            <PenLine className="h-3 w-3" />
                            Post it
                          </button>
                          <button
                            onClick={() => dismissAction(msg.id)}
                            className="rounded-lg bg-[var(--bg-tertiary)] px-2.5 py-1 text-micro text-[var(--text-secondary)] transition-colors hover:bg-[var(--bg-hover)]"
                          >
                            Not now
                          </button>
                        </>
                      )}
                      {msg.action.type === "post_prompt" && (
                        <button
                          onClick={() => prefillFromPrompt("Post: ")}
                          className="flex items-center gap-1 rounded-lg bg-[var(--bg-tertiary)] px-2.5 py-1 text-micro text-[var(--text-secondary)] transition-colors hover:bg-[var(--bg-hover)] hover:text-[var(--text-primary)]"
                        >
                          <PenLine className="h-3 w-3" />
                          Draft a post
                        </button>
                      )}
                      {msg.action.type === "follow_prompt" && (
                        <button
                          onClick={() => prefillFromPrompt("Find @")}
                          className="flex items-center gap-1 rounded-lg bg-[var(--bg-tertiary)] px-2.5 py-1 text-micro text-[var(--text-secondary)] transition-colors hover:bg-[var(--bg-hover)] hover:text-[var(--text-primary)]"
                        >
                          <UserPlus className="h-3 w-3" />
                          Find someone
                        </button>
                      )}
                      {msg.action.type === "message_prompt" && (
                        <button
                          onClick={() => prefillFromPrompt("Message @username: ")}
                          className="flex items-center gap-1 rounded-lg bg-[var(--bg-tertiary)] px-2.5 py-1 text-micro text-[var(--text-secondary)] transition-colors hover:bg-[var(--bg-hover)] hover:text-[var(--text-primary)]"
                        >
                          <MessageSquare className="h-3 w-3" />
                          Write a message
                        </button>
                      )}
                    </div>
                  )}
                </div>
              </motion.div>
              );
            })}

            {isTyping && (
              <motion.div
                initial={{ opacity: 0, x: -16, scale: 0.9 }}
                animate={{ opacity: 1, x: 0, scale: 1 }}
                transition={{ type: "spring", stiffness: 340, damping: 24 }}
                className="flex justify-start"
              >
                <div className="rounded-2xl rounded-bl-md border border-[var(--border-primary)] bg-[var(--bg-card)] px-4 py-3">
                  <div className="mesh-typing-wave" role="status" aria-label="Meshi is typing">
                    <span />
                    <span />
                    <span />
                  </div>
                </div>
              </motion.div>
            )}

            <div ref={messagesEndRef} />
          </div>

          {messages.length <= 2 && (
            <div className="border-t border-[var(--border-primary)] px-4 py-2" style={{ background: "var(--bg-secondary)" }}>
              <p className="mb-2 flex items-center gap-1 text-micro text-[var(--text-muted)]">
                <Sparkles className="h-3 w-3" />
                Start here
              </p>
              <div className="flex flex-wrap gap-1.5">
                {QUICK_ACTIONS.map((action) => {
                  const Icon = action.icon;
                  return (
                    <button
                      key={action.label}
                      onClick={() => handleSend(action.prompt)}
                      className="flex items-center gap-1 rounded-lg bg-[var(--bg-tertiary)] px-2 py-1 text-micro text-[var(--text-secondary)] transition-colors hover:bg-[var(--bg-hover)] hover:text-[var(--text-primary)]"
                    >
                      <Icon className="h-3 w-3" />
                      {action.label}
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          <div className="flex items-center gap-2 border-t border-[var(--border-primary)] px-4 py-3" style={{ background: "var(--bg-secondary)" }}>
            <input
              ref={inputRef}
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleSend()}
              placeholder="Ask me anything..."
              className="flex-1 rounded-xl border border-[var(--border-primary)] bg-[var(--bg-tertiary)] px-3 py-2 text-sm text-[var(--text-primary)] placeholder:text-[var(--text-muted)] focus:border-[var(--accent)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)]/30"
            />
            <button
              onClick={() => handleSend()}
              disabled={!input.trim() || isTyping}
              aria-label="Send message to Meshi"
              className="rounded-xl brand-button p-2 text-white transition-all hover:shadow-lg disabled:cursor-not-allowed disabled:opacity-40"
            >
              <Send className="h-4 w-4" />
            </button>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
