/**
 * CLAIM-TRUTH GATE — `npm run claim-truth:check`
 *
 * A product may not tell someone their data is private in a place where the code
 * sends it somewhere.
 *
 * This started as four separate wordings, all about Meshi, all shown at the exact
 * moment a person decides what to disclose:
 *
 *   - the Privacy Control Center's Meshi memory rule: "What Meshi can use
 *     LOCALLY to answer questions about your Mesh" — the governing statement for
 *     the switch being operated
 *   - the chat header pill: emerald, pulsing dot, the word "Private" — the visual
 *     grammar of a padlock
 *   - the header status: "Private companion"
 *   - the in-flight string, shown WHILE the request is in the air:
 *     "Reasoning privately..."
 *
 * Meanwhile src/lib/meshi-reasoning.ts POSTs the mesh context and the visible
 * post to api.openai.com. The repo's own consent module says so in as many words:
 * "a grounded answer is pasted verbatim into the OpenAI prompt".
 *
 * The copy was what changed, not the code — sending context to a reasoning
 * provider is what this feature has always been for, and the consent switch
 * genuinely works. But a false security indicator is worse than none, because it
 * is read precisely when someone is deciding whether to type something.
 *
 * ── WHAT THIS CANNOT PROVE ───────────────────────────────────────────────────
 *
 * It reads string literals in named files. It cannot evaluate whether a claim is
 * true — only whether a privacy-asserting word appears in Meshi-facing copy
 * without having been signed off here. Copy assembled from variables, loaded
 * from the database, or living in a file not listed below is invisible to it.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const read = (p: string) => readFileSync(join(ROOT, p), "utf8");

// ── 1. The premise: Meshi's reasoning really does leave the building ─────────
//
// If this ever stops being true — a local model, no provider — then the copy
// above is no longer false and this gate should be RELAXED deliberately, not
// left asserting something that has stopped applying.
const reasoning = read("src/lib/meshi-reasoning.ts");
assert.match(
  reasoning,
  /fetch\(\s*["'`]https:\/\/api\.openai\.com/,
  "src/lib/meshi-reasoning.ts no longer POSTs to an external provider.\n" +
    "  If Meshi's reasoning became local, this gate's whole premise changed — revisit the copy\n" +
    "  rules below deliberately rather than deleting this assertion.",
);

// ── 2. No Meshi-facing copy asserts privacy or locality ─────────────────────
//
// An exact allowlist rather than a word ban, because several legitimate strings
// contain these words — a quick-action prompt the USER sends ("How is my privacy
// looking?") is a question, not a promise. Pinning the set means a new string
// carrying one of these words fails until somebody reads it and decides.
const CLAIM_WORDS = /\b(private|privately|privacy|locally|local|on-device|never leaves|encrypted)\b/i;

const MESHI_SURFACES = [
  "src/components/meshi/meshi-chat.tsx",
  "src/components/meshi/meshi-float.tsx",
  "src/components/privacy/privacy-control-center.tsx",
];

// Every string literal in those files that contains one of the words above, and
// why it is allowed to. Keep the reason short and true.
const SIGNED_OFF: Record<string, string> = {
  "How is my privacy looking?": "a prompt the user sends, not a claim the product makes",
  "Privacy": "a quick-action button label — names the topic, asserts nothing",
  "Privacy controls": "navigation label",
  "What Meshi may use to answer questions about your Mesh, including sending it to the AI provider that generates Meshi's replies.":
    "the corrected Meshi memory rule — names the egress",
  "Meshi's replies are generated by a third-party AI provider. What Meshi may send is governed by your Meshi memory rule in Privacy controls.":
    "the chat pill's tooltip — states where replies come from",
  "Who can discover your identity outside direct shares.": "profile rule; no locality claim",
  "Default handling for posts created directly on Mesh.me.": "native-posts rule",
  "Message metadata and shared post privacy.": "MeChat rule; names the topic",
  "Performance data used inside the private analytics dashboard.":
    "the analytics dashboard genuinely is private to its owner — hasAnalyticsConsent gates the whole loader",
  "private": "a DataVisibilityPolicy enum value, not prose",
  "Local safety fallback":
    "true: source === 'local' is precisely the path where no provider was called",
  "Profile privacy saved.": "a save toast naming the setting; asserts no mechanism",
  "Only your already-public content is shared — nothing private.":
    "true, and shown beside a live preview of the exact items: every Global Mesh supply query in " +
    "src/lib/global-mesh.ts filters visibility:'public' behind isPublic + showInDiscovery, which " +
    "that module calls its zero-new-visibility invariant against a signed-out guest",
  "Hi. I'm Meshi. Ask me to search, explain, or help with your Mesh. You decide what I can see in Privacy controls.":
    "true and actionable: the Meshi memory switch genuinely gates both the grounding query and the egress",
};

/**
 * Blank comments while preserving offsets. Without this the gate reads its own
 * explanations: a comment saying `Not "Private companion" — …` contains a
 * quoted string, and the extractor cannot tell prose about copy from copy.
 */
function stripComments(text: string): string {
  return text
    .replace(/\/\*[\s\S]*?\*\//g, (m) => " ".repeat(m.length))
    .replace(/\/\/[^\n]*/g, (m) => " ".repeat(m.length));
}

const offenders: Array<{ file: string; text: string }> = [];
for (const file of MESHI_SURFACES) {
  const source = stripComments(read(file));
  // Double- and single-quoted literals plus non-interpolated template strings.
  // Deliberately dumb: it will not see a sentence built from variables, which is
  // stated as a limitation in the header rather than pretended away.
  const literals = [
    ...source.matchAll(/"((?:[^"\\\n]|\\.)*)"/g),
    ...source.matchAll(/'((?:[^'\\\n]|\\.)*)'/g),
    ...source.matchAll(/`([^`$\\]*)`/g),
  ].map((m) => m[1]);

  for (const raw of literals) {
    const text = raw.trim();
    // Skip class names, import paths, css vars, data attributes and enum-ish
    // fragments — none of these are read by a human as a sentence.
    if (!text || text.length < 4) continue;
    if (/^[\w./@-]+$/.test(text) && !SIGNED_OFF[text]) {
      if (/^(private|local)$/i.test(text)) {
        // fall through: these ARE meaningful as visible labels, check them
      } else continue;
    }
    if (text.includes("var(--") || text.includes("/") || text.includes(":")) continue;
    if (!CLAIM_WORDS.test(text)) continue;
    if (text in SIGNED_OFF) continue;
    offenders.push({ file, text });
  }
}

assert.deepEqual(
  offenders,
  [],
  "Meshi-facing copy asserts privacy, locality or encryption without being signed off:\n" +
    offenders.map((o) => `    ${o.file}\n      ${JSON.stringify(o.text)}`).join("\n") +
    "\n\n  Meshi's replies are generated by POSTing the mesh context to a third-party provider\n" +
    "  (asserted above). Copy shown where someone decides what to disclose must not say\n" +
    "  otherwise. Either reword it, or add it to SIGNED_OFF in scripts/claim-truth-check.ts\n" +
    "  with the reason it is actually true.",
);

// The specific four that were wrong, pinned so they cannot come back by hand.
// Comment-stripped, for the same reason as above: each of these lines now has a
// comment above it quoting the wording it replaced, and that is documentation,
// not copy. A gate that cannot tell the two apart forbids explaining itself.
const chat = stripComments(read("src/components/meshi/meshi-chat.tsx"));
const float = stripComments(read("src/components/meshi/meshi-float.tsx"));
const centre = stripComments(read("src/components/privacy/privacy-control-center.tsx"));
assert.ok(
  !/Reasoning privately/.test(float),
  '"Reasoning privately..." is shown WHILE the request is in flight to the provider — the one\n' +
    "  moment the word cannot be true.",
);
assert.ok(
  !/Private companion/.test(chat),
  '"Private companion" describes an assistant whose answers are generated off-box.',
);
assert.ok(
  !/can use locally to answer/.test(centre),
  'the Meshi memory rule must not say "locally" — it is the governing statement for the switch\n' +
    "  a person is operating, and the context goes to a provider.",
);
// The pill: no emerald + pulse. That combination is read as a security state,
// independent of the word inside it.
assert.ok(
  !/bg-emerald-500\/10[^"]*"[\s\S]{0,200}?animate-pulse[\s\S]{0,120}?Private/.test(chat),
  "the chat header must not render an emerald, pulsing 'Private' pill. That is the visual\n" +
    "  grammar of a padlock, and it sits directly above the input whose contents are sent\n" +
    "  to a third-party provider.",
);

// ── 3. The unauthenticated preview endpoint discloses the minimum ────────────
//
// /api/auth/meshi-preview answers anyone, with no session, for any username they
// can guess — src/proxy.ts does not list /api/auth as protected. It returned
// displayName, and the entry screen rendered it as "You're {displayName}."
const preview = stripComments(read("src/app/api/auth/meshi-preview/route.ts"));
assert.ok(
  !/displayName/.test(preview),
  "src/app/api/auth/meshi-preview/route.ts must not select or return displayName.\n" +
    "  It is unauthenticated by construction — it draws your Meshi before there is a session —\n" +
    "  so guessing a username handed an anonymous visitor a real name. The entry screen greets\n" +
    "  with the username the visitor typed instead, which they already know.",
);
assert.match(
  preview,
  /await durableRateLimit\(/,
  "the preview endpoint's rate limit IS its enumeration budget, so it must be the DURABLE one.\n" +
    "  The in-memory limiter is a per-process Map that resets on every serverless cold start.",
);
const entry = stripComments(read("src/components/auth/mesh-entry-experience.tsx"));
assert.ok(
  !/preview\?\.displayName/.test(entry),
  "the entry screen must not read displayName off the unauthenticated preview response.",
);

// A sign-off for copy that no longer exists is how an allowlist rots into
// permission for something nobody reviewed. If a string is reworded, its reason
// has to be re-read against the new wording, not inherited.
const stillPresent = new Set<string>();
for (const file of MESHI_SURFACES) {
  const source = stripComments(read(file));
  for (const text of Object.keys(SIGNED_OFF)) {
    if (source.includes(text)) stillPresent.add(text);
  }
}
const stale = Object.keys(SIGNED_OFF).filter((t) => !stillPresent.has(t));
assert.deepEqual(
  stale,
  [],
  "These strings are signed off in scripts/claim-truth-check.ts but no longer appear in any\n" +
    "Meshi-facing surface:\n" +
    stale.map((t) => `    ${JSON.stringify(t)}`).join("\n") +
    "\n  Drop the stale entry. A reason written for old wording is not a review of new wording.",
);

console.log(
  `claim-truth contract OK — Meshi's reasoning provably leaves the building, and no copy on\n` +
    `  ${MESHI_SURFACES.length} Meshi-facing surfaces claims otherwise (${Object.keys(SIGNED_OFF).length} strings signed off with reasons).\n` +
    "  The unauthenticated Meshi preview discloses no display name and uses the durable limiter.\n" +
    "  Does NOT cover: copy built from variables, loaded from the database, or in files not listed.",
);
