// THE STATUS PAGE MUST NOT CONTRADICT THE PRODUCT.
//
// This gate exists because production served this, from /api/system-status:
//
//   "overallStatus": "operational"
//   "summary": "All monitored Mesh.me systems are operational."
//   integrations → "operational" — "5 of 12 OAuth adapters have credentials
//                   available; connected-account storage is reachable."
//
// while the SAME deployment's Connect page showed a red panel reading
// "Connecting is switched off on this deployment ... An admin needs to set
// APP_DATA_ENCRYPTION_KEY". Both statements were generated by the same running
// server, and one of them was false.
//
// The cause was that the integrations check asked two questions that do not
// decide the outcome — do any OAuth client credentials exist, and does the
// connected-account table answer a count — and never asked the one that does.
// A provider token must be encrypted before it is stored, so with no key
// `/api/auth/[platform]` refuses to begin the flow and ZERO adapters can
// complete, however many have credentials.
//
// A green status page is a claim to the operator that the thing they are
// looking for is somewhere else. That is worse than no status page, and it is
// invisible to types, lint and build — the code was well-formed and said
// something untrue. So it is asserted here instead.
//
// Run: npm run status-truth:check

import assert from "node:assert/strict";

let n = 0;
function ok(condition: boolean, label: string): void {
  n++;
  assert.ok(condition, label);
}

/** The three env names `secret-store.getKey()` reads, in its order. All must be
 * cleared to simulate an unconfigured deployment — clearing only the first
 * would let a fallback silently keep the gate green. */
const KEY_VARS = ["APP_DATA_ENCRYPTION_KEY", "MESHME_TOKEN_ENCRYPTION_KEY", "MESHME_SECRET_KEY"] as const;

async function statusWithEnv(env: Record<string, string | undefined>) {
  const saved = new Map<string, string | undefined>();
  for (const [k, v] of Object.entries(env)) {
    saved.set(k, process.env[k]);
    if (v === undefined) delete process.env[k];
    else process.env[k] = v;
  }
  try {
    // Imported fresh each time: `getKey()` reads process.env at call time, but
    // re-importing keeps this honest if that ever becomes module-level.
    const mod = await import(`../src/lib/system-status?probe=${Math.random()}`);
    return await mod.getPublicSystemStatus();
  } finally {
    for (const [k, v] of saved) {
      if (v === undefined) delete process.env[k];
      else process.env[k] = v;
    }
  }
}

type Check = { id: string; status: string; detail: string };
type Status = { overallStatus: string; summary: string; checks: Check[] };

async function main() {
  // ── 1. NO KEY → INTEGRATIONS IS NOT GREEN ────────────────────────────────
  {
    const cleared = Object.fromEntries(KEY_VARS.map((k) => [k, undefined]));
    const status: Status = await statusWithEnv(cleared);
    const integrations = status.checks.find((c) => c.id === "integrations");

    ok(!!integrations, "the status payload still carries an integrations check");
    ok(
      integrations!.status !== "operational",
      `with no encryption key, integrations must not report operational (got "${integrations!.status}")`,
    );
    ok(
      status.overallStatus !== "operational",
      `…and the deployment as a whole must not report operational (got "${status.overallStatus}")`,
    );
    ok(
      status.summary !== "All monitored Mesh.me systems are operational.",
      "…and must not claim all systems are operational",
    );

    // The detail has to be ACTIONABLE. An operator reading this should not have
    // to grep the codebase to learn which variable is missing.
    ok(
      integrations!.detail.includes("APP_DATA_ENCRYPTION_KEY"),
      "the integrations detail names the exact variable an admin must set",
    );
    ok(
      /connect/i.test(integrations!.detail),
      "…and says plainly that connecting is affected, in the product's own words",
    );
  }

  // ── 2. A KEY THE STORE REJECTS COUNTS AS NO KEY ──────────────────────────
  //
  // `getKey()` accepts 64 hex characters, base64 decoding to 32 bytes, or utf8
  // of exactly 32 bytes — and in production it refuses the SHA-256 passphrase
  // fallback outright. So a key that LOOKS set can still be no key at all.
  // Reading the variable rather than calling the store would miss this, which
  // is the mistake one layer up: `launch:check` asserts the variable is
  // "configured and is a usable 32-byte key", and passes locally against a
  // .env.local that production does not share.
  {
    const bogus = Object.fromEntries(KEY_VARS.map((k) => [k, undefined])) as Record<string, string | undefined>;
    bogus.APP_DATA_ENCRYPTION_KEY = "too-short-to-be-a-key";
    const status: Status = await statusWithEnv(bogus);
    const integrations = status.checks.find((c) => c.id === "integrations")!;
    ok(
      integrations.status !== "operational",
      `a key the secret store rejects must read as unconfigured, not operational (got "${integrations.status}")`,
    );
  }

  // ── 3. A REAL KEY DOES NOT TRIP IT ───────────────────────────────────────
  //
  // The gate must be able to pass, or it is just a broken build. 64 hex
  // characters is what LAUNCH-GUIDE.md tells an operator to generate.
  {
    const good = Object.fromEntries(KEY_VARS.map((k) => [k, undefined])) as Record<string, string | undefined>;
    good.APP_DATA_ENCRYPTION_KEY = "a".repeat(64);
    const status: Status = await statusWithEnv(good);
    const integrations = status.checks.find((c) => c.id === "integrations")!;
    ok(
      integrations.status === "operational" || integrations.detail.includes("provider credentials"),
      `with a valid key, integrations is gated only on provider credentials (got "${integrations.status}": ${integrations.detail})`,
    );
    ok(
      !integrations.detail.includes("APP_DATA_ENCRYPTION_KEY"),
      "…and stops telling the operator to set a key that is already set",
    );
  }

  console.log(`status truth OK — ${n} assertions (the status page cannot claim green while connecting is off)`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
